cuisine_map = {
  'Afghan': 'Afghanistan',
  'Albanian': 'Albania',
  'Algerian': 'Algeria',
  'Amharic': 'Ethiopia',
  'Anguillan': 'Anguilla',
  'Argentine': 'Argentina',
  'Armenian': 'Armenia', 
  'Australian': 'Australia',
  'Austrian': 'Austria',
  'Azerbaijani': 'Azerbaijan',
  'Bahamian': 'Bahamas',
  'Bangladeshi': 'Bangladesh',
  'Barbadian': 'Barbados',
  'Basque': 'Basque Country',
  'Belarusian': 'Belarus',
  'Belgian': 'Belgium',
  'Belizean': 'Belize',
  'Beninese': 'Benin',
  'Bhutanese': 'Bhutan',
  'Bolivian': 'Bolivia',
  'Bosnian': 'Bosnia and Herzegovina',
  'Botswanan': 'Botswana',
  'Brazilian': 'Brazil',
  'British': 'United Kingdom',
  'Bruneian': 'Brunei',
  'Bulgarian': 'Bulgaria',
  'Burkinabe': 'Burkina Faso', 
  'Burmese': 'Myanmar',
  'Burundian': 'Burundi',
  'Cambodian': 'Cambodia',
  'Cameroonian': 'Cameroon',
  'Canadian': 'Canada',
  'Cape Verdean': 'Cape Verde',
  'Central African': 'Central African Republic',
  'Chadian': 'Chad',
  'Chilean': 'Chile',
  'Chinese': 'China',
  'Colombian': 'Colombia',
  'Comorian': 'Comoros',
  'Congolese': 'Congo',
  'Costa Rican': 'Costa Rica',
  'Croatian': 'Croatia',
  'Cuban': 'Cuba',
  'Cypriot': 'Cyprus',
  'Czech': 'Czech Republic',
  'Danish': 'Denmark',
  'Djiboutian': 'Djibouti',
  'Dominican': 'Dominican Republic',
  'Dutch': 'Netherlands',
  'East Timorese': 'East Timor',
  'Ecuadorian': 'Ecuador',
  'Egyptian': 'Egypt',
  'Emirati': 'United Arab Emirates', 
  'Eritrean': 'Eritrea',
  'Estonian': 'Estonia',
  'Ethiopian': 'Ethiopia',
  'Fijian': 'Fiji',
  'Filipino': 'Philippines',
  'Finnish': 'Finland',
  'Flemish': 'Flanders',
  'French': 'France',
  'Gabonese': 'Gabon',
  'Gambian': 'Gambia',
  'Georgian': 'Georgia',
  'German': 'Germany',
  'Ghanaian': 'Ghana',
  'Greek': 'Greece',
  'Grenadian': 'Grenada', 
  'Guatemalan': 'Guatemala',
  'Guinean': 'Guinea',
  'Guyanese': 'Guyana',
  'Haitian': 'Haiti',
  'Herzegovinian': 'Bosnia and Herzegovina',
  'Honduran': 'Honduras',
  'Hungarian': 'Hungary',
  'Icelandic': 'Iceland',
  'Indian': 'India',
  'Indonesian': 'Indonesia',
  'Iranian': 'Iran',
  'Iraqi': 'Iraq',
  'Irish': 'Ireland',
  'Israeli': 'Israel',
  'Italian': 'Italy',
  'Ivorian': 'Ivory Coast',
  'Jamaican': 'Jamaica',
  'Japanese': 'Japan', 
  'Jordanian': 'Jordan',
  'Kazakh': 'Kazakhstan',
  'Kenyan': 'Kenya',
  'Kittian and Nevisian': 'St. Kitts and Nevis',
  'Kosovar': 'Kosovo', 
  'Kuwaiti': 'Kuwait',
  'Kyrgyz': 'Kyrgyzstan',
  'Laotian': 'Laos',
  'Latvian': 'Latvia',
  'Lebanese': 'Lebanon',
  'Lesotho': 'Lesotho',
  'Liberian': 'Liberia',
  'Libyan': 'Libya',
  'Liechtensteiner': 'Liechtenstein',
  'Lithuanian': 'Lithuania',
  'Luxembourgish': 'Luxembourg',
  'Macedonian': 'North Macedonia',
  'Malagasy': 'Madagascar',
  'Malawian': 'Malawi',
  'Malaysian': 'Malaysia',
  'Maldivian': 'Maldives',
  'Malian': 'Mali',
  'Maltese': 'Malta',
  'Marshallese': 'Marshall Islands',
  'Mauritanian': 'Mauritania',
  'Mauritian': 'Mauritius', 
  'Mexican': 'Mexico',
  'Micronesian': 'Micronesia',
  'Moldovan': 'Moldova',
  'Monacan': 'Monaco',
  'Mongolian': 'Mongolia',
  'Montenegrin': 'Montenegro',
  'Moroccan': 'Morocco',
  'Mozambican': 'Mozambique',
  'Namibian': 'Namibia',
  'Nauruan': 'Nauru',
  'Nepalese': 'Nepal',
  'New Zealand': 'New Zealand',
  'Nicaraguan': 'Nicaragua',
  'Nigerien': 'Niger',
  'Nigerian': 'Nigeria',
  'North Korean': 'North Korea',
  'Northern Irish': 'North Ireland',
  'Norwegian': 'Norway',
  'Omani': 'Oman',
  'Pakistani': 'Pakistan', 
  'Palestinian': 'Palestine',
  'Panamanian': 'Panama',
  'Papua New Guinean': 'Papua New Guinea',
  'Paraguayan': 'Paraguay',
  'Peruvian': 'Peru',
  'Polish': 'Poland',
  'Portuguese': 'Portugal',
  'Qatari': 'Qatar',
  'Romanian': 'Romania',
  'Russian': 'Russia', 
  'Rwandan': 'Rwanda',
  'Saint Lucian': 'Saint Lucia',
  'Salvadoran': 'El Salvador',
  'Samoan': 'Samoa',
  'San Marinese': 'San Marino',
  'Sao Tomean': 'Sao Tome and Principe',
  'Saudi': 'Saudi Arabia',
  'Scottish': 'Scotland',
  'Senegalese': 'Senegal',
  'Serbian': 'Serbia',
  'Seychellois': 'Seychelles',
  'Sierra Leonean': 'Sierra Leone',
  'Singaporean': 'Singapore',
  'Slovak': 'Slovakia',
  'Slovenian': 'Slovenia',
  'Solomon Islander': 'Solomon Islands',
  'Somali': 'Somalia',
  'South African': 'South Africa',
  'South Korean': 'South Korea',
  'South Sudanese': 'South Sudan',
  'Spanish': 'Spain',
  'Sri Lankan': 'Sri Lanka',
  'Sudanese': 'Sudan',
  'Surinamese': 'Suriname',
  'Swazi': 'Swaziland',
  'Swedish': 'Sweden',
  'Swiss': 'Switzerland',
  'Syrian': 'Syria',
  'Taiwanese': 'Taiwan',
  'Tajik': 'Tajikistan',
  'Tanzanian': 'Tanzania',
  'Thai': 'Thailand',
  'Togolese': 'Togo',
  'Tongan': 'Tonga',
  'Trinidadian': 'Trinidad and Tobago', 
  'Tunisian': 'Tunisia',
  'Turkish': 'Turkey', 
  'Tuvaluan': 'Tuvalu',
  'Ugandan': 'Uganda',
  'Ukrainian': 'Ukraine',
  'Uruguayan': 'Uruguay',
  'Uzbek': 'Uzbekistan',
  'Venezuelan': 'Venezuela',
  'Vietnamese': 'Vietnam',
  'Welsh': 'Wales',
  'Yemeni': 'Yemen',
  'Zambian': 'Zambia',
  'Zimbabwean': 'Zimbabwe'
}